이메일 회원가입#1
Friends77/FRI-FRONT pull request #25
Opened 2024-12-13 08:52 UTC by itsmesunky

## ⭐ Key Changes
- 이메일 입력 시, 해당 이메일로 인증 코드를 전송하는 API를 연동했습니다.
- 사용자가 입력한 인증 코드를 서버로 보내 유효한 코드인지 확인하는 API를 연동했습니다.
- ~~모든 입력 값(이메일, 인증 코드, 비밀번호)이 유효해야 다음 단계 진행이 가능하도록 폼 검증 로직을 추가했습니다.~~
- ~~공통 컴포넌트 `Input`에 prop을 추가하였습니다.~~
- `RHF`를 활용하여 폼 관리를 진행하였습니다.

## 🖐️To reviewers
- 이메일을 통해 인증 코드를 전송하고, 이를 확인하는 기능을 구현했습니다.
- 코드 리뷰 시, 입력 값 검증 로직과 Recoil을 활용한 전역 상태 관리, API 연동 부분에 대해 피드백 주시면 감사하겠습니다.

## 📌issue
close #1

2024-12-13 11:20 UTC, GangHub1970 requested changes
수고하셨습니다 👍
최대한 열심히 리뷰 작성해봤습니다...! 어쩔 수 없이 길어진것 같은데 조금 길긴하네요..🔥 리뷰가 부족할 수 있을 것 같아요.

2024-12-13 11:20 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
> +  const signUpValue = useRecoilValue(signUpAtom);
`useRecoilState`을 사용해서 한번에 처리하는 방법을 사용하는건 어떨까요??

2024-12-13 11:20 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
> +  const [isVerifiedCode, setIsVerifyCode] = useState(false);
상태 변경 함수를 `isVerifiedCode`에 `set`을 추가한 것이 아니라 `setIsVerifyCode`로 조금 다르게하신 이유가 있을까요??

2024-12-13 11:20 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
> +  const [isCertNoSended, setIsCertNoSended] = useState(false);
`isCertNoSended`가 인증번호가 보내졌는지를 저장하는 변수인가요?? 영어로 어떤걸 나타내는지 헷갈리는데 알려주시면 감사하겠습니다!!

2024-12-13 11:20 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
> +    data.acquisition = acquisitionChannel;
혹시 이 부분에서 `acquisition`가 무엇을 의미하나요?? 폼 데이터에 `acquisition`에 대한 값은 없는거 같아서요!!

2024-12-13 11:20 UTC, GangHub1970 commented on src/recoil/signup/atom.ts
> +const signUpAtom = atom({
이 `atom`이 회원가입에 필요한 정보를 저장하는 상태라면 조금 더 직관적으로 알 수 있게 네이밍하면 좋을 것 같은데 어떻게 생각하시나요?
`signUpData` 또는 `signUpFormData`, `signUpProfileData`이런식으로...? (예시입니다!)

2024-12-13 11:20 UTC, GangHub1970 commented on src/recoil/signup/atom.ts
> +  key: "signUpAtom",
`atom`의 `key`값에서 `Atom`이라는 접미사는 삭제하고 하는건 어떨까요?? 별로라면 제가 `isLoggedIn` 상태를 변경하겠습니다! 이건 그냥 선택인것 같아요 ㅎㅎ

2024-12-13 11:20 UTC, GangHub1970 commented on src/pages/signup/root/index.tsx
이 레이아웃 컴포넌트는 어떤 상황에서 사용될 수 있을까요? 나중에 쓰일 것 같긴한데 아직 이렇게 구현해본적이 없어서 잘 모르겠네요! 만약 지금처럼 아무 기능이 없어도 나중을 위해 만드시는게 좋다면 다른 페이지에서도 만들어야 할 것 같아요!!

2024-12-13 11:20 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
혹시 `react-hook-form`을 사용하시지 않는 이유가 있을까요?
근데 `<Input>` 컴포넌트를 만드셔서 적용하기가 애매한것 같긴하네요..! 이 문제는 지원님이랑 다같이 이야기해봐야 할 것 같아요 🤔

2024-12-13 11:20 UTC, GangHub1970 commented on src/apis/auth/index.ts
저는 나중에 `useQuery`로 데이터 가져올 때 이 api 요청 함수에서 반환값을 지정해놓으면 거기서 따로 타입을 지정하지 않아도 바로 사용가능해서 미리 `login` 만들 때 반환값을 지정해놨는데, 보통 프로젝트 진행하실 때 어떻게 하셨나요??

2024-12-13 15:53 UTC, itsmesunky commented on src/pages/signup/signup/index.tsx
> +  const signUpValue = useRecoilValue(signUpAtom);
리뷰 감사드립니다! 🙇

이번에 `recoil`을 처음 사용해 보면서 급하게 공부하느라, `useRecoilValue`로 값을 가져오고 `useSetRecoilState`로 값을 설정해야 하는 줄 알았어요. 😢

`useRecoilState` 하나로 값을 가져오고 설정까지 할 수 있다는 걸 알게 되었네요ㅎㅎ
다시 공식 문서를 찬찬히 봐야겠어요❗

2024-12-13 15:53 UTC, itsmesunky commented on src/pages/signup/signup/index.tsx
> +  const [isVerifiedCode, setIsVerifyCode] = useState(false);
오타입니다 😅 수정하도록 하겠습니다!

2024-12-13 15:53 UTC, itsmesunky commented on src/pages/signup/signup/index.tsx
> +  const [isCertNoSended, setIsCertNoSended] = useState(false);
피드백 감사합니다❗ ❗
각 상태 관리 변수마다 주석을 추가하도록 하겠습니다.

2024-12-13 15:53 UTC, itsmesunky commented on src/pages/signup/signup/index.tsx
> +    data.acquisition = acquisitionChannel;
<img width="329" alt="스크린샷 2024-12-14 오전 12 30 19" src="https://github.com/user-attachments/assets/9d5374ae-af9b-48be-bf21-bcdb5fc2a625" />

에고 이 부분은 추후 페이지 아래에 추가될 동의 체크박스 요소의 `name`인데
아직 디자인과 기획 측에서 합의가 안 된 것 같아서 주석 처리한다는걸 깜빡했네요.

프로젝트에 위치 정보 제공 받는 기능도 들어가는걸로 알고 있어서 해당 부분은 그대로 두고,
나머지 코드도 함께 올려놓겠습니다.

2024-12-13 15:54 UTC, itsmesunky commented on src/recoil/signup/atom.ts
> +const signUpAtom = atom({
좋습니다! 😃

제가 네이밍 센스가 부족해서 지원님이랑 윤강님 덕분에 많이 배워가고 있어요ㅎㅎ
감사합니다!! 🙇

2024-12-13 15:54 UTC, itsmesunky commented on src/recoil/signup/atom.ts
> +  key: "signUpAtom",
넵 그렇게 수정하도록 하겠습니다. 👍👍

2024-12-13 15:54 UTC, itsmesunky commented on src/pages/signup/root/index.tsx
피그마의 회원가입 플로우를 보면 회원가입 페이지가 중첩 라우팅이 될 것 같아서
해당 레이아웃 컴포넌트에서 `Outlet`을 선언하려고 만들었습니다.

2024-12-13 15:54 UTC, itsmesunky commented on src/pages/signup/signup/index.tsx
`react-hook-form`을 예전에 사용해본 기억으로는 커스터마이징이 잘 되지 않았던 것 같아서
이번에는 `useInput` 커스텀 훅을 직접 만들어서 유효성 검사를 진행했습니다.

2024-12-13 15:54 UTC, itsmesunky commented on src/apis/auth/index.ts
```typescript
export async function login({
  email,
  password,
}: LoginDataType): Promise<LoginResponse> {
  const response = await Axios.post("/api/auth/login", {
    email,
    password,
  });

  return response.data;
}
```
이 코드에서 `response.data` 부분에 대해 여쭤보시는 거라면, 저도 동일하게 진행했습니다.

2024-12-14 03:08 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
> +  const [isCertNoSended, setIsCertNoSended] = useState(false);
피드백 반영 감사드립니다 ㅎㅎㅎ
그런데 `isCertNoSended`는 `No`가 있으니까 `인증 번호가 발송되지 않은 경우`에 `true`가 되는건가요?
아니면 `No`가 제가 생각하는 부정의 `No`가 아닌가요??

2024-12-14 03:08 UTC, GangHub1970 commented on src/recoil/signup/atom.ts
> +const signUpFormData = atom({
앗.. `key`값에서 `Atom`을 제외하는 방법을 제안드린거였습니다.😅

2024-12-14 03:08 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
> +    data.acquisition = acquisitionChannel;
아하 감사합니다 ㅎㅎ
그런데 `data.acquisition = acquisitionChannel;`이 코드는 어떤 의도로 작성하신 걸까요?
제가 콘솔찍어보면 이 코드를 실행하기 전에도 `data`에 `acquisition`이 들어있는것 같아서요!!

2024-12-14 03:15 UTC, GangHub1970 commented on src/apis/auth/index.ts
함수 반환값 타입 `: Promise<LoginResponse>` 이 부분을 말씀드린겁니다!

2024-12-14 03:37 UTC, itsmesunky commented on src/pages/signup/signup/index.tsx
> +  const [isCertNoSended, setIsCertNoSended] = useState(false);
아 certNo는 cert + number 합성어입니다!

2024-12-14 03:40 UTC, itsmesunky commented on src/pages/signup/signup/index.tsx
> +    data.acquisition = acquisitionChannel;
Object.fromEntries(fd.entries()) => form 태그 안의 모든 input 요소의 name과 value과 객체화 됩니다!

그 객체에 input 요소중 체크박스에 체크한 값을 배열로 추가하기 위해 사용된 코드입니더.

2024-12-14 03:41 UTC, itsmesunky commented on src/apis/auth/index.ts
타 프로젝트에서는 반환값을 미리 지정해놓지는 않았습니다.

2024-12-15 09:38 UTC, itsmesunky commented on src/recoil/signup/atom.ts
> +const signUpFormData = atom({
수정했습니다아

2024-12-19 09:24 UTC, iamkjw77 requested changes
리액트 훅폼으로 빠르게 변경해주셨네요👍
고생하셨습니다!

2024-12-19 09:24 UTC, iamkjw77 commented on src/pages/signup/signup/index.tsx
페이지 폴더 컨벤션에 맞춰서 `/src/pages/auth/signIn/index.tsx`로 생성하는게 좋을 것 같습니다!

2024-12-19 09:24 UTC, iamkjw77 commented on src/pages/signup/signup/index.tsx
> +            <Button disabled={!isValid} onClick={handleNextStep}>
지금도 너무 좋지만, 버튼도 <AuthForm />에 같이 넣으면 깔끔할 것 같습니다. 
특별히 버튼만 빼신 이유가 있을까요?

2024-12-19 09:24 UTC, iamkjw77 commented on src/recoil/signup/atom.ts
폴더구조 컨벤션에 맞춰서 `/src/recoil/auth/signup/atom.ts`로 맞추는 것이 좋을 것 같습니다.

2024-12-19 10:05 UTC, GangHub1970 requested changes
`react-hook-form` 사용해서 입력폼 만드신다고 고생하셨습니다..!!! 👍

2024-12-19 10:05 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
혹시 실무에서는 `react-hook-form`이런 폼관리 라이브러리는 거의 사용되지 않나요??
통일을 해야하니까 저나 선우님 중에 한명이 코드를 변경하거나 만드신 `<Input>` 컴포넌트에 `react-hook-form`를 적용시키는 방법 중에 선택해야될 것 같네요..

2024-12-19 10:05 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
> +    data.acquisition = acquisitionChannel;
아 이해했습니다!!!

2024-12-19 10:05 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
> +  const [isCertNoSended, setIsCertNoSended] = useState(false);
아하 number가 no로 쓰일 수도 있네요.. 😅

2024-12-19 10:05 UTC, GangHub1970 commented on src/pages/signup/signup/index.tsx
> +import ProfileForm from "@/components/signup/Form/ProfileForm";
여기 주소가 제대로 안되어 있는것 같은데 확인부탁드립니다!!

만들 컴포넌트를 표시하신 걸까요??

2024-12-19 10:05 UTC, GangHub1970 commented on src/components/signup/Form/AuthForm.tsx
> +  const [isTImerActive, setIsTimerActive] = useState(false);
`isTImerActive`에서 `I`가 오타인것같아요!

2024-12-19 10:05 UTC, GangHub1970 commented on src/components/signup/Input/InputField.tsx
`react-hook-form` 잘 적용해서 만드신것 같아요..!! 👍

`IInputProps`가 컨벤션에 맞게 `IInputFieldProps`로 변경되면 좋을것 같습니다!

2024-12-19 10:05 UTC, GangHub1970 commented on src/components/signup/Form/AuthForm.tsx
에러 메세지나 정규표현식은 상수화해서 사용하는거에 대해서 어떻게 생각하세요?? 패턴은 저번에 하기로했던 것 같고, 에러 메세지는 이야기했는지 모르겠습니다..!

이 브랜치가 로그인 기능 만들기 전에 만들어져서 `constants/message/index.ts`가 없었던것 같습니다. `develop` 브랜치에는 만들어져 있는것 같습니다. 괜찮다고 생각하시면 아래코드 사용해서 수정부탁드립다!
```javascript
// 인증 관련 에러 메세지
export const AUTH_ERROR_MSG = Object.freeze({
  EMAIL_REQUIRED: "이메일을 입력해주세요.",
  EMAIL_PATTERN: "이메일 형식이 아닙니다.",
  PASSWORD_REQUIRED: "비밀번호를 입력해주세요.",
  INCORRECT_EMAIL_OR_PASSWORD:
    "아이디 또는 비밀번호가 잘못 되었습니다. 아이디와 비밀번호를 정확히 입력해 주세요.",
});
```
(지금 확인해보니 `freeze`는 빠져있었는데 넣어서 만들고 사용해주시면 될 것 같습니다)

2024-12-19 10:58 UTC, itsmesunky commented on src/pages/signup/signup/index.tsx
피드백 감사합니다.

말씀 주신 부분 수정하였습니다!

2024-12-19 11:03 UTC, itsmesunky commented on src/pages/signup/signup/index.tsx
> +            <Button disabled={!isValid} onClick={handleNextStep}>
각 **Form**마다 **Recoil** 상태를 주입해서 관리하기보다 부모 컴포넌트에서 한 번에 관리하는 게 좋다고 생각해서 그렇게 구현했습니다!

근데 말씀하신 대로 버튼도 Form 안에 넣는 게 코드가 더 깔끔해 보이네요!

폼 이동 함수는 **유틸리티 함수화**하고, 각 **Form**에서 **Recoil**로 회원가입 단계 상태를 관리하도록 수정해보았습니다.
제가 생각한 로직은 이런데, 혹시 다른 의견 있으시면 말씀 부탁드립니다!

2024-12-19 11:04 UTC, itsmesunky commented on src/recoil/signup/atom.ts
넵! 컨벤션이 아직 익숙하지 않아서 실수가 많네요. 😢
앞으로 더 신경 쓸 수 있도록 하겠습니다!

2024-12-19 11:05 UTC, itsmesunky commented on src/pages/signup/signup/index.tsx
> +import ProfileForm from "@/components/signup/Form/ProfileForm";
리뷰 감사합니다!

해당 파일도 같이 올렸습니다.

2024-12-19 11:07 UTC, itsmesunky commented on src/components/signup/Form/AuthForm.tsx
> +  const [isTImerActive, setIsTimerActive] = useState(false);
수정했습니다, 늘 꼼꼼하게 봐주셔서 감사합니다! 😢

2024-12-19 11:07 UTC, itsmesunky commented on src/components/signup/Input/InputField.tsx
원래 컴포넌트명이 Input이었다가 InputField로 바꿨는데 type명까지는 캐치를 못했네요.
감사합니다! 👍👍

2024-12-19 11:11 UTC, itsmesunky commented on src/components/signup/Form/AuthForm.tsx
넵 반영해서 수정했습니다! 이번에는 `AUTH_ERROR_MSG`에 **placeholder**를 함께 넣었는데 만약, **placeholder** 상수화 하는 것도 괜찮으시면, 다음 번엔 분리해서 상수화하는 게 좋을 것 같네요!

2024-12-19 11:12 UTC, iamkjw77 approved these changes

2024-12-19 11:37 UTC, GangHub1970 commented on src/components/signup/Form/AuthForm.tsx
네 더 많아진다면 상수화하는 것도 괜찮을것 같아요!!

2024-12-19 11:37 UTC, GangHub1970 approved these changes

2024-12-19 12:14 UTC, merged