ImagePicker 컴포넌트 생성#27
Friends77/FRI-FRONT pull request #30
Opened 2024-12-20 10:42 UTC by itsmesunky

## ⭐ Key Changes
- 회원가입 후 프로필 설정에서 사용할 **Image Picker** 컴포넌트를 생성했습니다.
## 🖐️To reviewers
- 원래는 **dropdown** 컴포넌트도 직접 구현할 예정이었으나, `react-select`를 사용하는 곳이 적합하다고 판단되어 **dropdown**은 `react-select`로 구현할 예정입니다.
- 혹시 `react-select` 이 외에 더 나은 대안이나 제안이 있다면 리뷰로 공유 부탁드립니다!
## 📌issue
close #27

2024-12-20 14:02 UTC, iamkjw77 requested changes

2024-12-20 14:02 UTC, iamkjw77 commented on src/components/signup/ImagePicker/ImagePicker.tsx
이번에 컴포넌트 구조를 보면서 뒤늦게 컨벤션에 관해 리뷰드린 점 양해부탁드립니다.
컨벤션에 따라서 컴포넌트 폴더가 아래와 같이 바뀌어야 할 것 같아요.  

버튼 외에 인풋, 이미지 픽커가 auth에만 쓰일 것 같지 않아서 공통 컴포넌트로 위치시켰습니다.
Button => @common/Button/index.tsx
Input => @common/Input/index.tsx
ImagePicker => @common/ImagePicker/index.tsx

AuthForm => auth/Form/AuthForm/index.tsx
ProfileForm => auth/Form/ProfileForm/index.tsx
Timer => auth/Timer/index.tsx

이 구조를 이번 pr에서 하는게 적용하는게 좋을지 아니면 제가 따로 하는게 좋을지 의견주시면 감사하겠습니다.
프로젝트 초반이라서 컨벤션에 관한 리뷰가 많아지네요. 
초반에 잘 구조화두면 이후에는 컨벤션 관련 리뷰는 적어질 것 같습니다😂

2024-12-20 14:02 UTC, iamkjw77 commented on src/components/signup/ImagePicker/ImagePicker.tsx
> +    <div>
지금 디자인된 프로필 설정 이미지 픽커는 '이미지 변경' 버튼은 없고, 이미지 자체를 선택해서 프로필을 변경하는 것처럼 보입니다.
아직 디자인을 적용하지 않은 컴포넌트 이겠지만, div 보다는 label로 태그를 바꾸면 useRef를 사용하지 않아도 될 것 같습니다.

2024-12-20 14:02 UTC, iamkjw77 commented on src/components/signup/ImagePicker/ImagePicker.tsx
> +        style={{ display: "none" }}
```suggestion
```
style 속성을 제거하고, hidden 속성을 추가하면 웹 접근성 측면에서 더 좋을 것 같습니다.

2024-12-20 14:02 UTC, iamkjw77 commented on src/components/signup/ImagePicker/ImagePicker.tsx
> +  const buttonClickHandler = () => {
이제 컴포넌트가 많아지면서 이벤트 핸들러 네이밍 컨벤션도 필요할 것 같아 노션에 정리해서 올려두었습니다.

2024-12-20 14:02 UTC, iamkjw77 commented on src/components/signup/ImagePicker/ImagePicker.tsx
> +    if (!file) {
```suggestion
if (file) {
      const fileReader = new FileReader();

      fileReader.onload = () => {
        if (typeof fileReader.result === 'string') {
          setPickedImage(fileReader.result);
        }
      };

      fileReader.readAsDataURL(file);

      setValue(name, file);
}
```
파일이 있는 경우로 if문을 바꾸면 파일이 없는 경우 코드는 없어져도 될 것 같은데, 위 방법은 어떤지 의견 부탁드립니다!

2024-12-20 15:00 UTC, itsmesunky commented on src/components/signup/ImagePicker/ImagePicker.tsx
> +    <div>
바쁘신 와중에 리뷰 감사합니다! 🙇

### **Image Picker** 구조
제가 만든 **Image Picker**는 이미지 미리보기 영역에서 absolute한 위치에 **버튼**을 두고,
이를 클릭해 이미지를 변경하는 구조로 설계했습니다.
(추후 퍼블리싱 작업에서는 `button`대신`img`로 대체할 계획입니다.)

혹시 지원님께서 말씀하신 `디자인된 프로필 설정 이미지 픽커`는 어떤 디자인을 말씀 하시는 건지 알 수 있을까요? 
- - -

### `ref` 대신 `label` 사용
아래 리뷰 내용과 관련이 있는데요,

`ref`를 사용해 클릭 이벤트를 트리거하게 되면 이미지 선택 여부와 관계없이
`input` 요소의 `onChange` 에 할당된 함수가 실행됩니다.

반면, `label`의 `htmlFor`속성과 `input` 요소의 `id`를 매칭하는 방식으로 구현하면,
이미지를 선택했을 때만 `onChange` 함수가 실행되는 걸로 알고 있습니다!
(혹시 제가 잘못 알고 있는 부분이 있다면 말씀 부탁드립니다! 🙏 )

그래서, `onChange`에 할당된 함수에
```typescript
if(!file) {
...
}
```
같은 검증 로직을 추가했는데요,

이 부분에서 **이미지를 선택하지 않을 경우 기본 이미지로 돌아갈지,**
**아니면 기존 이미지를 유지할지**에 대해서는 기획 및 디자인팀과 추가 논의가 필요할 것 같습니다!

- - -

#### 제가 참고한 Image Picker 디자인입니다.

<img width="364" alt="image" src="https://github.com/user-attachments/assets/e8b80da9-72c4-44ff-b710-59d968950494" />

<img width="425" alt="image" src="https://github.com/user-attachments/assets/ff4700a2-ec8c-4918-bfad-5cbdfcfc0f45" />

2024-12-20 15:00 UTC, itsmesunky commented on src/components/signup/ImagePicker/ImagePicker.tsx
> +        style={{ display: "none" }}
그렇게 변경하는 것이 더 좋을 것 같아요! 리뷰 감사합니다 👍👍

2024-12-20 15:05 UTC, itsmesunky commented on src/components/signup/ImagePicker/ImagePicker.tsx
> +  const buttonClickHandler = () => {
참고해서 수정했습니다! 컨벤션 정리해주셔서 감사드려요.
초반에는 익숙해지는 데 시간이 조금 걸릴 수도 있겠지만, 나중에는 훨씬 깔끔하고 효율적으로 작업할 수 있을 것 같아요.

2024-12-20 15:22 UTC, itsmesunky commented on src/components/signup/ImagePicker/ImagePicker.tsx
제 사견으로는, 디자인팀에서 **Foundation**을 정의해준 게 없다 보니
저희끼리 어떤 컴포넌트를 프로젝트 전반에 공통적으로 사용할지 정하는 건 다소 어려운 상황인 것 같습니다.

제가 설계한 **ImagePicker** 컴포넌트도 프로필 작성 쪽에서만 쓰이고 있어서
공통 컴포넌트로 분리하기에는 무리가 있다고 판단해 `auth`에 넣어뒀어요.
**Input**도 비슷한 이유로 공통으로 빼기엔 애매하더라고요.

- - -
### 현재 디자인된 input
![image](https://github.com/user-attachments/assets/557d6633-4c55-4fcd-88d9-987950b8777e)
![image](https://github.com/user-attachments/assets/3506b397-64a1-4e45-8fe4-84f5764a47b4)
![image](https://github.com/user-attachments/assets/f497627e-b420-4666-90ec-113c73ed5780)
![image](https://github.com/user-attachments/assets/d57ee0a0-5d78-4e86-baba-030362c90a20)

- - -


Foundation 정의 없이 프로젝트를 진행해본 적은 처음인데, 이런 경우엔 어떻게 진행하셨는지 궁금합니다!

~~~
AuthForm => auth/Form/AuthForm/index.tsx
ProfileForm => auth/Form/ProfileForm/index.tsx
Timer => auth/Timer/index.tsx
~~~

이 부분은 제 pr에 반영해서 수정하도록 하겠습니다.

2024-12-20 15:52 UTC, iamkjw77 requested changes

2024-12-20 15:52 UTC, iamkjw77 commented on src/components/signup/ImagePicker/ImagePicker.tsx
> +    <div>
제가 본 디자인도 같은 디자인인 것 같습니다. 
label을 사용할 경우 이미지 유무와 관계없이 onChange 함수를 실행할 수 있습니다.  
따라서 위 디자인과 같이 구현한다면 삭제버튼만 추가해서 삭제 이벤트 핸들러에 
위 코드에서 file이 없을 때 코드를 넣으면 될 것 같습니다.

```suggestion
<label htmlFor={name}>
        {pickedImage ? (
          <img src={pickedImage} alt={`${name} preview`} />
        ) : (
          <p>기본 이미지</p>
        )}
        <input
          hidden
          id={name}
          type="file"
          {...register(name)}
          ref={imageInput}
          onChange={handleImageChange}
        />
        {/* 아이콘 버튼 */}
        {/* <AddPhotoIcon /> */}
</label>
```

2024-12-20 15:52 UTC, iamkjw77 commented on src/components/signup/ImagePicker/ImagePicker.tsx
그렇군요. 저는 막연하게 채팅과 회원가입에 사용하는 인풋 컴포넌트는 동일하다고 생각했던 것 같습니다.(이미지 피커 또한 마찬가지 입니다)

저도 디자인 시스템 Foundation 없이 진행했던 적은 없었지만, 공통적으로 쓰는 컴포넌트는 페이지가 조금씩 쌓이면서 추가된 적도 있어서 디자인도 저희도 확실하게 어떤 컴포넌트가 공통 컴포넌트인지 판단하기에는 어려울 수 있을 것 같습니다. 

추후에 해당 컴포넌트가 다른 곳에서 또 쓰이면 그때 공통 컴포넌트로 이동하는 것도 좋을 것 같습니다.

2024-12-20 16:18 UTC, itsmesunky commented on src/components/signup/ImagePicker/ImagePicker.tsx
> +    <div>
늦은 시간에 리뷰 감사합니다 🙇

저는 `label`과 `input` 태그의 사용법은 아래처럼만 사용하던 터라,
`input`을 `label`로 감싸는 방법은 생각해보지 못했네요.

```html
<label for=""></label>
<input />
```

덕분에 새로운 방식도 알게 되었어요.
이렇게 하니까 정말 깔끔하게 동작하네요! 감사합니다. 👍👍

2024-12-20 16:18 UTC, itsmesunky commented on src/components/signup/ImagePicker/ImagePicker.tsx
> +    if (!file) {
넵 말씀하신대로 수정했습니다! 👍👍👍

2024-12-20 16:29 UTC, iamkjw77 approved these changes
고생하셨습니다👍

2024-12-21 00:56 UTC, GangHub1970 approved these changes
수고하셨습니다!! 👍

제가 더 피드백 드릴 수 있는 부분은 없어보입니다..!

2024-12-21 03:31 UTC, merged