로그인 페이지 입력폼 컴포넌트 적용
Friends77/FRI-FRONT pull request #31
Opened 2024-12-21 07:29 UTC by GangHub1970

## ⭐ Key Changes

- 로그인 페이지의 입력폼에 `<InputField>` 컴포넌트를 적용했습니다.

## 🖐️To reviewers

- `<InputField>`가 만들어지기 전에 만든 로그인 페이지의 입력창에 `<InputField>`을 적용시켰습니다.
- 로그인 페이지(`<LoginPage>`)에서 직접 폼을 컨트롤하기 보단 폼에 관한 로직은 분리하는게 더 좋겠다는 생각이 들어 `<LoginForm>` 컴포넌트를 분리했습니다.

## 📌issue

close #28

2024-12-21 14:21 UTC, iamkjw77 requested changes

2024-12-21 14:21 UTC, iamkjw77 commented on src/components/AuthInterceptor/index.tsx
`component/auth/AuthInterceptor/index.tsx` auth와 관련된 컴포넌트라서 auth 안에 들어가야 할 것 같습니다.

2024-12-21 14:21 UTC, iamkjw77 commented on src/components/TokenRefresher/index.tsx
`component/auth/TokenRefresher/index.tsx` 위 리뷰 내용과 동일합니다.

2024-12-21 14:47 UTC, GangHub1970 commented on src/components/AuthInterceptor/index.tsx
전체를 감싸는 느낌이라 밖에 나뒀었는데 `auth`안에 들어가는게 맞을 것 같습니다..! 수정했습니다.
좀 더 신중하게 작성하도록 하겠습니다!🙏🏻

2024-12-21 15:03 UTC, iamkjw77 approved these changes
열심히 하시는 모습이 너무 보기좋습니다. 고생하셨습니다👍

2024-12-22 04:36 UTC, itsmesunky approved these changes
고생하셨습니다! 👍

2024-12-22 05:10 UTC, merged