비밀번호 찾기/변경 페이지 구현
Friends77/FRI-FRONT pull request #32
Opened 2024-12-22 07:02 UTC by GangHub1970

## ⭐ Key Changes

- 비밀번호 찾기/변경 페이지를 구현했습니다.
- 회원가입 페이지와 동일하게 `/reset-password` 페이지에서 컴포넌트를 단계별로 구분하여 비밀번호 찾기(이메일 인증) -> 비밀번호 변경 순서로 진행될 수 있게 구현했습니다.

## 🖐️To reviewers

- 회원가입 페이지와 거의 동일한 코드가 많아서 컴포넌트를 분리해야할 것 같은데 이번 PR에서 코드 변경이 너무 많아질 것 같아 먼저 PR 올리고 따로 해보겠습니다!!
- 회원가입 페이지에서는 하나의 `useForm`에서 `email`, `certno`, `password`, `confirm-password`을 관리하지만 비밀번호 찾기 페이지에서는 마지막에 이메일을 보낼 필요가 없기 때문에 각 단계별로 `useForm`을 만들어 `email, certno`와 `password, confirm-password` 을 따로 관리했습니다.
- `EmailVerificationForm`의 `handleSendEmail`에서 `trigger`를 통해 유효성 검사 실행 후 실패하면 이후 이메일을 수정해도 에러가 사라지지 않아서 `useEffect`를 사용해서 에러를 삭제했습니다.
  ```javascript
  useEffect(() => {
    // handleSendEmail의 trigger 이후 email 입력란에 변화가 생기면 다시 유효성 검사를 진행
    if (errors.email) {
      clearErrors("email");
    }
  }, [email, errors]);
  ```
  찾아봐도 잘 안나와서 이렇게 밖에 구현을 못했는데 원래 `trigger` 후에는 이렇게 에러를 직접 삭제해줘야 할까요..? 혹시 아시는 다른 방법이 있다면 피드백 주시면 감사하겠습니다..!!! 🙏🏻🙏🏻
- 지금은 `resetPasswordStepAtom`, `signUpStepAtom` 단계가 정해져있는데 제한?이 없으니까 아래 코드처럼 타입을 지정해주는건 어떻게 생각하시나요? 사실 저 값을 벗어나는 상황은 없을 것 같긴해서 필요없다고 생각하시면 추가하지 않겠습니다!
  ```javascript
  const resetPasswordStepAtom = atom<1 | 2>({
    key: "resetPasswordStep",
    default: 1,
  });
  ```

## 📌issue

close #29

2024-12-22 16:56 UTC, iamkjw77 requested changes

2024-12-22 16:56 UTC, iamkjw77 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  useEffect(() => {
```suggestion

```
인증요청 버튼을 누르면 이메일은 수정할 수 없게 disabled 처리를 하는 기획이 필요할 것 같습니다.
만약 지금과 같이 이메일 인증버튼을 누른 후에 이메일을 수정할 수 있다면 고려해야 할 부분이 너무 많아질 것 같습니다.

2024-12-22 16:56 UTC, iamkjw77 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  const handleSendEmail = async () => {
인증요청 버튼의 disabled 상태에서 !!errors.email이면(유효성 검사에 실패하면) 버튼이 disabled 될 것 같은데, 인증요청 전 한 번 더 유효성 검사를 하는 이유가 있을까요?

2024-12-22 16:56 UTC, iamkjw77 commented on src/components/auth/Form/ResetPasswordForm/index.tsx
> +  useEffect(() => {
```suggestion

```
새 비밀번호 확인 인풋 validate에서 비밀번호 일치 여부 확인을 하는 것 같은데, 
이 부분(useEffect)에서 비밀번호 일치 여부를 확인하는 이유가 있을까요?

2024-12-22 16:56 UTC, iamkjw77 commented on src/components/auth/Form/ResetPasswordForm/index.tsx
> +        <Button disabled={!isPasswordEqual}>확인</Button>
```suggestion
        <Button disabled={!!errors['confirm-password']}>확인</Button>
```
이 부분에서 errors를 사용해도 좋을 것 같습니다!

2024-12-23 01:46 UTC, itsmesunky requested changes
고생하셨습니다👍

2024-12-23 01:46 UTC, itsmesunky commented on src/components/auth/Form/EmailVerificationForm/index.tsx
코드 실행해보니 가입하지 않은 이메일에도 인증 코드가 발송되는 문제가 있네요..! 😢  

이 부분은 백엔드에서 이메일 발송 전에 가입된 이메일인지 확인하는 로직을 추가하거나,  
현재 나와 있는 API(`/api/auth/check-email`)를 활용해 프론트 단에서 인증 코드 발송 로직을 수정하는 방식으로 해결 가능할 것 같습니다.  

개인적으로는 이메일 발송 전 검증 로직을 백엔드에서 처리해 주시는 게 UX와 효율성 측면에서 더 좋을 것 같아요.  
다른 분들 의견도 궁금합니다! 😊

2024-12-23 01:46 UTC, itsmesunky commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  const methods = useForm({
useForm 훅의 매개변수로 `mode: "onChange"`를 추가하면 `trigger`를 사용하지 않고도 쉽게 해결이 가능할 것 같은데,  
혹시 `onChange`를 사용하지 않으신 특별한 이유가 있으실까요? 😊

2024-12-23 01:46 UTC, itsmesunky commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +          rules={{
여기 minLength 조건이 빠져있어서 한 글자만 입력해도 다음 버튼이 활성화 되는 문제가 있어서 수정이 필요해보입니다!

2024-12-23 04:28 UTC, GangHub1970 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  useEffect(() => {
이메일이 정상적으로 유효성 검사를 통과하고 이메일을 보내면 이메일 입력란과 "인증요청" 버튼은 `disabled`가 되게 구현했습니다!

`useEffect`는 "인증 요청"을 클릭하고 API 요청 전에 유효성 검사에서 에러가 발생한 경우에 추가적인 이메일 수정을 위해 작성한 코드입니다.

혹시 제가 피드백을 잘못이해했을까요??

2024-12-23 04:37 UTC, GangHub1970 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  const handleSendEmail = async () => {
제가 `useForm`의 `mode`를 `onChange`로 사용하지 않아서 초기에 한 번 제출하기 전까지는 입력할 때마다 유효성 검사를 진행하지 않는것으로 알고 있습니다. 그릐고 "인증 요청" 버튼이 `submit` 버튼이 아니라서 버튼을 눌러도 유효성 검사를 진행하지 않아 `trigger`를 통해 유효성 검사를 진행했습니다.

한 `<form`안에 두개의 입력이 있는데 각자 따로 제출을 해야해서 버튼을 `button` 타입으로 지정했습니다.
"인증 요청" 버튼만 `submit`으로 두고 클릭 시에 폼을 제출하면 아직 인증코드를 입력하지 않아서 인증코드 입력란에서 에러가 발생한 것처럼 동작해 위 방법으로 구현했습니다.

2024-12-23 05:07 UTC, GangHub1970 commented on src/components/auth/Form/ResetPasswordForm/index.tsx
> +  useEffect(() => {
피드백 감사드립니다!!
그 부분은 미처 확인하지 못했습니다. 피드백 반영해서 push했습니다. 🙏🏻

2024-12-23 05:29 UTC, GangHub1970 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
이건 저도 백엔드에서 처리해주는게 좋을것 같아요. 지금 만들어진 API의 의도랑은 다르게 사용해야해서 처리할 때 어색한 부분이 있을것 같네요.

추가적으로 비밀번호 변경할 때 기존 비밀번호로 변경해도 지금은 동작하는데, 이게 맞을까요? 저는 동일한 비밀번호로 변경은 안되는게 맞다고 생각하는데 의견주시면 감사하겠습니다!!

2024-12-23 05:52 UTC, GangHub1970 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +          rules={{
감사합니다. `minLength` 유효성 검사 추가했고, 추가적으로 이메일 보내기전에 인증코드 입력을 `disabled`로 막았습니다!

2024-12-23 05:53 UTC, GangHub1970 commented on src/components/auth/Form/ResetPasswordForm/index.tsx
> +        <Button disabled={!isPasswordEqual}>확인</Button>
반영했습니다. 감사합니다!

2024-12-23 06:22 UTC, GangHub1970 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  const methods = useForm({
저는 `onChange`를 사용하면 처음 사용자가 입력을 시작할 때부터 에러 메세지가 떠서 그게 별로라고 생각해서 기본값(`onSubmit`)으로 사용했습니다..!

피드백 주신대로 `onChange`를 사용하면 `trigger`와 `useEffect` 없이 구현이 간단하게 가능은 합니다!! 저의 생각에 대해선 어떻게 생각하시나요?

2024-12-23 06:44 UTC, itsmesunky commented on src/components/auth/Form/EmailVerificationForm/index.tsx
네, 동의합니다! 동일한 비밀번호로 변경하지 못하게 막는 게 보안적으로 더 적합해 보이네요.

백엔드 팀원분들께 해당 로직 추가를 요청드리면 좋을 것 같습니다! 😊

2024-12-23 06:49 UTC, itsmesunky commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  const methods = useForm({
음 맞아요..! 😊 `onChange`는 ux 측면에서 좀 아쉽긴 한 거 같아요,,

그냥 `trggier`를 사용하신 이유가 궁금해서 여쭤본건데, 지금 방식으로 진행해도 충분히 괜찮을 것 같아요!

2024-12-23 06:50 UTC, itsmesunky approved these changes

2024-12-23 07:01 UTC, GangHub1970 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  const methods = useForm({
감사합니다!!

2024-12-23 08:41 UTC, iamkjw77 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  useEffect(() => {
지금은 이메일 인증버튼을 누르고 이메일 인증이 완료되면 이메일 인풋이 disabled 되지만, 
인증버튼을 누르고 인증이 완료되기 전까지 이메일 인풋을 변경할 수 있는 여지가 있어서
인증 버튼을 누르는 순간 이메일 인풋이 disabled 되야할 것 같습니다.

2024-12-23 08:53 UTC, iamkjw77 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  const handleSendEmail = async () => {
https://github.com/Friends77/FRI-FRONT/pull/32#discussion_r1895302274

위 리뷰에서 나누신 대화를 보고 mode: "onSubmit"을 사용하신 이유는 이해했습니다.
저도 공감은 가지만, 회원가입에서 onChange 모드를 사용해 구현이 되었고
이 부분에서는 onSubmit 모드로 구현이 되어서 인풋 통일성이 깨진다는 점이 약간 걸리기는 하네요...

2024-12-25 03:25 UTC, GangHub1970 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  useEffect(() => {
그부분을 생각 못 했네요! 피드백 감사드립니다..!!

2024-12-25 03:28 UTC, GangHub1970 commented on src/components/auth/Form/EmailVerificationForm/index.tsx
> +  const handleSendEmail = async () => {
그러면 통일성을 위해 `onChange`로 변경하고 혹시 나중에 리팩터링할 수 있다면 방법을 생각해보겠습니다!! 물론 지금 방법이 괜찮다면 그냥 나둬도 좋아요 👍

2024-12-25 14:20 UTC, iamkjw77 approved these changes
고생하셨습니다👍

2024-12-26 03:35 UTC, merged