소셜 로그인 기능 개발
Friends77/FRI-FRONT pull request #39
Opened 2024-12-27 11:02 UTC by iamkjw77

## ⭐ Key Changes
- 소셜(구글, 네이버) 로그인 기능 개발

## 🖐️To reviewers
- 로그인 페이지 진입하면, RT 요청으로 인해 400에러가 발생하는데, TokenRefresher 컴포넌트에서 AT이 존재하거나, 로그인이나 회원가입 같은 페이지에서는 refresh() 요청을 하지 않아도 될 것 같은데 의견 부탁드립니다.

## 📌issue

close #33

2024-12-27 14:51 UTC, itsmesunky reviewed
https://www.notion.so/hosung-note/bc4101ce9d1f4b33b704caacac0dd7b1

기능 구현에 사용된 환경 변수 값 공유 부탁드립니다!

2024-12-27 15:11 UTC, iamkjw77 commented
> https://www.notion.so/hosung-note/bc4101ce9d1f4b33b704caacac0dd7b1
> 
> 기능 구현에 사용된 환경 변수 값 공유 부탁드립니다!

노션에 추가해 두었습니다!

2024-12-28 04:25 UTC, itsmesunky requested changes

2024-12-28 04:25 UTC, itsmesunky commented on src/recoil/auth/socialLogin/atom.ts
<img width="383" alt="image" src="https://github.com/user-attachments/assets/10ba4fba-7e83-4ab7-9ca2-ce7885a31e9f" />

recoil 폴더 구조와 관련해서, 컨벤션 상 **atom 파일과 index 파일을 따로 생성**하기로 했던 것으로 기억합니다.
해당 PR에서는 index 파일이 누락된 것 같은데, 확인 부탁드려요!  😊

2024-12-28 04:25 UTC, itsmesunky commented on src/pages/auth/callback/naver/index.tsx
이 파일은 네이버 로그인이 성공한 뒤 redirect 되는 페이지로 사용되나요?
제가 확인했을 때 해당 페이지가 사용되는 곳을 찾지 못했는데, 혹시 어떤 용도로 사용되는 걸까요?

2024-12-28 04:25 UTC, itsmesunky commented on src/hooks/auth/useSocialLogin.ts
<img width="870" alt="image" src="https://github.com/user-attachments/assets/ce4b867d-0b29-4f6b-b022-c760383f131f" />

구글 로그인 시 **COOP 오류**가 발생하는 것 같은데, 이 부분의 원인에 대해 설명해 주실 수 있을까요?

2024-12-28 09:19 UTC, iamkjw77 commented on src/recoil/auth/socialLogin/atom.ts
일단 제가 의도한 컨벤션은 `recoil/[feature]/index.tsx` 하나만 만들고 그 안에 관련된 atom이나 selector 등을 다 넣는 방식을 생각했습니다. 그런데 지금 구성된 recoil 폴더 방식(`/src/recoil/auth/accessToken/atom.ts`, `/src/recoil/auth/accessToken/withIsLoggedIn.ts`)처럼 atom과 selector를 분리해서 파일을 구성하니 accessToken과 관련된 recoil을 한 눈에 볼 수 있어 좋다라는 생각이 들었습니다.

이번에 프로젝트를 진행하면서 그동안 코드리뷰에서 캐치하지 못했던 `/src/recoil/auth/accessToken/index.ts`와 같은 파일을 자세하게 들여다보게 되었는데, 각 폴더에(/src/auth/[feature]) index.ts 파일이 존재하지 않아도 될 것 같다는 생각이 들었습니다.

index.ts가 필요한 이유가 특별한 이유없이 제가 작성한 컨벤션 때문이라면, 해당 부분을 제거하는 작업이 필요할 것 같습니다. 

제가 작성한 컨벤션에 대한 충분한 논의가 없어서, 발생한 문제 같습니다🥲
의견 부탁드립니다! @itsmesunky @GangHub1970

2024-12-28 09:22 UTC, iamkjw77 commented on src/pages/auth/callback/naver/index.tsx
넵 이해하신 대로 이 파일은 네이버 로그인 성공한 뒤 redirect 되는 페이지로 사용됩니다.
네이버 로그인 성공 => `http://localhost:3000/oauth/naver/callback?code=blablabla&state=:r1:`

2024-12-28 10:37 UTC, iamkjw77 commented on src/hooks/auth/useSocialLogin.ts
이 부분을 제가 미처 보지 못했네요. 검색해본 결과 해당 오류는 아래와 같은 이유 때문에 발생한다고 합니다.

```
해당 오류는 구글의 OAuth 팝업창과 애플리케이션 창 사이의 상호 작용 때문에 발생하고, 브라우저는 보안상의 이유로 이러한 상호 작용을 제한하려고 합니다.

이 오류는 브라우저의 보안 정책과 관련된 것으로, Cross-Origin-Opener-Policy(COOP)가 window.closed 호출을 차단하려고 할 때 발생합니다. 하지만 이 오류 메시지가 나타나더라도 대부분의 경우 구글 로그인 기능은 정상적으로 작동합니다.
```

해당 오류가 나타나도 구글 로그인은 정상적으로 작동하긴 하나, 오류가 난다는 것은 어쨋든 보안 상 위험이 있다는 것으로 판단되어 구글 로그인을 팝업창 대신 네이버 로그인처럼 리다이렉트로 다시 수정하여 올려두었습니다!

2024-12-28 11:07 UTC, GangHub1970 requested changes

2024-12-28 11:07 UTC, GangHub1970 commented on src/apis/auth/index.ts
> +  const response = await Axios.post<ISocialLoginResponse>("/api/auth/oauth2", {
api 요청 response에 대한 타입을 설정할거면 나머지 요청 함수에도 추가하는게 좋을 것 같은데, 저번에 선우님은 다른 프로젝트에서 타입 지정을 안하고 진행하셨다고 하셨던것 같은데 지원님은 반환 데이터 interface를 지정하는게 좋다고 생각하시나요?

저는 개인적으로 좋다고 생각하는데 두분은 어떠신지 궁금하네요! 그리고 통일을 하는게 좋을 것 같아요..! @iamkjw77 @itsmesunky

2024-12-28 11:07 UTC, GangHub1970 commented on src/components/auth/Form/LoginForm/index.tsx
제가 `LoginForm` 컴포넌트를 추가적인 버튼이나 디자인 요소들이랑 구분하기 위해서 만들었었는데, 로그인 관련된 버튼은 맞지만 `LoginForm`에서는 분리해서 버튼을 추가하는게 좋을 것 같다는 생각이 드는데 어떻게 생각하시나요?

2024-12-28 11:07 UTC, GangHub1970 commented on src/recoil/auth/socialLogin/atom.ts
선우님께서 말씀해주신 부분이 제가 제안드렸던 부분입니다. 지원님이 처음에 말씀해주신 장점이 해당 폴더 구조를 사용하는 제일 큰 이유였고, `index.ts`가 존재하는 이유는 각각을 사용하는 곳에서 불러와서 사용할 때 `import`구문이 너무 길어질 수 있다는 점을 보완하기 위함입니다. `index.ts`에서 한번에 `export`해주면 `/src/recoil/auth/accessToken`이 주소에서 atom, selector 모두를 import할 수 있다는 장점이 있어서 코드가 좀 더 깔끔해질 것 같습니다.

물론 지금은 selector가 너무 없어서 저도 `index.ts` 파일을 만들며 불필요하다고 느끼긴했지만 앞으로 확장성을 고려했을때는 미리 적용해놓는게 좋다고 판단하여 사용했었습니다.

아래 블로그를 보고 폴더구조를 적용한 것입니다. 한번 읽어보시면 좋을 것 같아요! 읽어보시고 의견주시면 감사하겠습니다..!!(제가 설명드리는 것보다 훨씬 이해가 잘 되실거라 생각합니다..😂)
https://parkjju.github.io/vue-TIL/daily/220703-recoil.html

2024-12-28 11:12 UTC, GangHub1970 commented
`TokenRefresher`을 로그인, 회원가입 페이지에서 실행되지 않게 하는 부분은 제가 수정해서 PR 날리겠습니다!!

`refresh` 요청이 새로고침되는 순간에 실행되는 것이기 때문에 `AT`가 있는 경우에도 실행해서 토큰을 재발급 받는건 괜찮다고 생각하는데 어떠신가요?

2024-12-28 15:46 UTC, iamkjw77 commented on src/recoil/auth/socialLogin/atom.ts
넵 그렇군요. 블로그 포스팅을 읽어 보니 이해가 쉽게 갔습니다👍
윤강님 말씀대로 지금은 selector가 별로없어서 index.ts의 필요가 거의 없어보이지만 
확장성을 고려하면 필요할 것 같습니다. 

index.ts 파일을 추가해 두었습니다!

2024-12-28 15:55 UTC, iamkjw77 commented on src/apis/auth/index.ts
> +  const response = await Axios.post<ISocialLoginResponse>("/api/auth/oauth2", {
저도 타입 지정을 하는게 좋을 것 같습니다. 

예시로 타입을 지정하면 위 sendSocialLoginToken api를 사용하는 useSocialLogin 훅에서 
onSuccess시에 파라미터 값을 자동완성 할 수 있어서 편리한 것 같습니다.

2024-12-28 15:59 UTC, iamkjw77 commented on src/components/auth/Form/LoginForm/index.tsx
넵 저도 그게 좋을 것 같습니다.
분리해서 적용해두었습니다!

2024-12-28 16:24 UTC, iamkjw77 commented
AT가 있는 경우에는 refresh 요청을 하지 않아도 될 것 같습니다🤔

AT가 있는데 만료된 경우, 401 에러가 발생하면서 refresh 요청을 통해 AT 교체가 일어나기 때문에
AT가 있는 경우에는 refresh 요청을 하지 않아도 될 것 같은데, 
혹시 AT가 있는 경우 refresh를 요청해야 하는 다른 경우가 있을까요?

2024-12-29 02:15 UTC, itsmesunky commented on src/apis/auth/index.ts
> +  const response = await Axios.post<ISocialLoginResponse>("/api/auth/oauth2", {
앗 그럼 반환 데이터에 interface 지정하는 걸로 가시죠! 👍

2024-12-29 02:49 UTC, itsmesunky approved these changes
고생하셨습니다! 👍

2024-12-29 03:11 UTC, GangHub1970 commented
사용자가 새로고침했으니까 토큰도 그 시간을 기준으로 재발급되는게 좋지 않을까라고 생각했던것 같습니다. 그런데 지원님 말씀대로 굳이 필요는 없는 요청이라.. 그 부분도 수정해서 올리겠습니다!! 👍

2024-12-29 03:13 UTC, GangHub1970 approved these changes
수고하셨습니다 👍

2024-12-29 07:25 UTC, merged