로그인, 비밀번호 찾기 페이지 디자인
Friends77/FRI-FRONT pull request #45
Opened 2024-12-31 14:41 UTC by GangHub1970

## ⭐ Key Changes

- 로그인 페이지에 스타일을 입혔습니다.
  <img width="1440" alt="스크린샷 2024-12-31 오후 11 17 58" src="https://github.com/user-attachments/assets/dcebd255-e99c-4d2d-a3be-4bb044b32ea3" />

- 비밀번호 찾기 페이지에 스타일을 입혔습니다.
  <div align="center">
  <img width="50%" alt="스크린샷 2024-12-31 오후 11 26 20" src="https://github.com/user-attachments/assets/6ea53ac4-f69f-4d72-be85-e2b866e3275d" />
  <img width="50%" alt="스크린샷 2024-12-31 오후 11 38 37" src="https://github.com/user-attachments/assets/43dfdb44-af01-4f31-9441-f3d92d3d3b2c" />
</div>

- 공통 컴포넌트 `<Input>`에 스타일을 입혔습니다.
  - 기본적인 스타일과 입력중에 나타나는 삭제(x) 버튼, 에러 메세지 등을 적용했습니다.
  - `width`를 `props`로 받아 설정할 수 있게 구현했습니다.

- 공통 컴포넌트 `<Button>`에 스타일을 입혔습니다.
  - 피그마에 `<SmallButton>`이 있어 따로 구현했습니다. `<Input>` 처럼 `width`를 받아서 구현하려했으나, 폰트에 대한 설정이 모두 달라서 따로 생성했습니다.

## 🖐️To reviewers

- 위 이미지는 노트북 화면이 작아서 축소해서 캡처한 화면입니다. 참고해주시기 바랍니다..!
- `styled-components`를 처음 사용해봐서 부족한 부분이 많을 수 있을 것 같습니다. 이상한 부분이나 더 효율적인 부분이 보이시면 피드백 주시면 적용해보도록 하겠습니다!
- 디스코드에서 이야기 나눴던 `<Input>`의 라벨 부분에 `boldLabel`을 추가했습니다. `labelWeight`로 하지 않은 이유는 `font-weight`만 다른것이 아니었기 때문에 `boldLabel`가 더 적절하다고 생각했습니다. + `isMandatory`도 추가했습니다.

## 📌issue

close #44

2025-01-01 06:43 UTC, iamkjw77 requested changes
고생하셨습니다👍 
스타일드 컴포넌트를 잘 사용하신 것 같아요!☺️

2025-01-01 06:43 UTC, iamkjw77 commented on src/components/@common/Button/Button/Button.styled.ts
> +  width: 320px;
width를 props로 받아서 사용하면, width가 다른 동일한 버튼에 재사용할 수 있을 것 같습니다.

2025-01-01 06:43 UTC, iamkjw77 commented on src/components/@common/Button/Button/Button.styled.ts
로그인, 회원가입, 비밀번호 찾기 페이지에서 버튼을 크게 `인증 요청` 버튼과 `다음` 버튼으로 나눌 수 있을 것 같은데,
이 부분을 `Button`과 `SmallButton`처럼 크기로 나누는 것보다 `PrimaryButton`, `SecondaryButton`으로 나누는 것은 어떨까요?

인증 요청은 다음 버튼에 비해 부차적인 버튼처럼 보여서 위와 같이 명명해보았습니다.

2025-01-01 06:43 UTC, iamkjw77 commented on src/components/@common/Button/SmallButton/SmallButton.styled.ts
> +  width: 102px;
이 부분도 위와 동일하게 width를 props로 받으면, 재사용에 용이할 것 같습니다.

2025-01-01 06:43 UTC, iamkjw77 commented on src/components/auth/Input/index.tsx
> +  isMandatory?: boolean;
```suggestion
  isRequired?: boolean;
```
필수적인 값을 사용할 때, `isRequired`를 많이 사용한 기억이 있어 남겨봅니다☺️

2025-01-01 06:43 UTC, iamkjw77 commented on src/components/auth/Input/index.tsx
> +  const handleCancleClick = () => {
```suggestion
  const handleCancelClick = () => {
```
오타가 있는 것 같습니다.

2025-01-01 12:15 UTC, GangHub1970 commented on src/components/@common/Button/Button/Button.styled.ts
아 그러면 `PrimaryButton`, `SecondaryButton`로 나누고 `width`를 두 버튼 모두 `props`로 받는게 좋겠다는 말씀이시죠??

그게 더 좋을것 같아서 수정했습니다!

2025-01-01 12:21 UTC, GangHub1970 commented on src/components/auth/Input/index.tsx
> +  isMandatory?: boolean;
에러 메세지 처리할 때도 필수항목에 `required`를 사용했으니 `required`가 더 좋을 것 같습니다! 감사합니다 👍

2025-01-01 12:21 UTC, GangHub1970 commented on src/components/auth/Input/index.tsx
> +  const handleCancleClick = () => {
죄송합니다. 🙏🏻 수정했습니다!

2025-01-01 12:49 UTC, iamkjw77 requested changes

2025-01-01 12:49 UTC, iamkjw77 commented on src/components/@common/Button/PrimaryButton/index.tsx
> +  extends React.ButtonHTMLAttributes<HTMLButtonElement> {}
```suggestion
  extends React.ButtonHTMLAttributes<HTMLButtonElement> {
    /** 버튼 disabled */
    disabled: boolean;
    /** 버튼 width */
    width: string;
  }
```
`PrimaryButton`, `SecondaryButton` props 타입에 어떤 props를 받는지 명시하면 어떤 props를 줄 수 있는지 스타일 파일까지 들어가지 않고도 알 수 있을 것 같아 편리할 것 같습니다☺️

2025-01-01 13:12 UTC, GangHub1970 commented on src/components/@common/Button/PrimaryButton/index.tsx
> +  extends React.ButtonHTMLAttributes<HTMLButtonElement> {}
전체적으로 제가 추가한 props에 대해 네이밍을 통해 명확하게 알기 어려운 것에 주석을 추가했습니다!! 😅

disabled의 경우는 제가 따로 받는게 아니라 `React.ButtonHTMLAttributes<HTMLButtonElement>`에서 제공되는 것이라 따로 주석처리하지 않았습니다..!

2025-01-01 13:21 UTC, iamkjw77 approved these changes

2025-01-02 00:36 UTC, itsmesunky approved these changes
고생하셨습니다!

전반적으로 깔끔하게 작성해주셔서 리뷰할 때 편했던 것 같아요👍👍

2025-01-02 00:36 UTC, itsmesunky commented on src/components/@common/Button/PrimaryButton/PrimaryButton.styled.ts
> +export const Button = styled.button<{ $width?: string }>`
퍼블리싱 코드 전체적으로 확인했습니다!
작업하실 때 prop 앞에 `$`를 붙여주셨더라고요.

저는 지금까지 `$`를 사용해본 적이 없어서 의미가 궁금했는데,
공식 문서를 확인해보니 styled components에서 스타일 관련 prop임을 나타내는 관례로 사용하더라고요!
(덕분에 공식 문서를 다시 한 번 확인해보는 기회가 되었습니다! 🙇)

코드 일관성을 위해 팀 내에서 이 부분에 대한 컨벤션을 정하면 좋을 것 같아요.
개인적으로는 `$`를 사용하는 방식이 가독성이나 명확성 면에서 더 좋아 보입니다!

2025-01-02 02:26 UTC, GangHub1970 commented on src/components/@common/Button/PrimaryButton/PrimaryButton.styled.ts
> +export const Button = styled.button<{ $width?: string }>`
저도 공식문서에 나와있는 방식이니 그대로 저희 컨벤션에 적용하는것이 좋아 보입니다! 기존에 props로 받는 다른 값들과 구분도 되고 좋은것 같아요. 😊

2025-01-02 08:17 UTC, merged